# OWNERSHIP=Claude
CXX ?= g++
# -mpopcnt: count bits with the CPU instruction (every x86-64 CPU since 2008) instead of
# a libgcc call; ~26% fewer search instructions. tools/match.cpp and speed_compare.cpp match it.
# -fwhole-program: every binary is one translation unit, so functions it never calls are
# dropped before they are optimised; ~15-25% less compile time, same bench, same nps.
CXXFLAGS ?= -O3 -mpopcnt -fwhole-program -Wall -Wno-unknown-pragmas -Wno-parentheses -Wno-unused-variable -DNDEBUG

TARGET ?= ascaniusfish
MAIN := ascaniusfish.cpp
UCI_TARGET := ascaniusfish_uci
HEADERS := $(wildcard *.hpp lib/*.hpp)
SOURCES := $(wildcard src/*.cpp)
TEST_SOURCES := hash_table_test.cpp hash_game_test.cpp pv_first_move_diagnostic.cpp
TEST_TARGETS := hash_table_test hash_game_test pv_first_move_diagnostic
PROFILE_ITERATIONS ?= 1
PROFILE_DEPTH ?= 100000
PERFT_DEPTH ?=
BENCH_DEPTH ?=
NNE ?=
ROUNDS ?= 10
DEPTH ?=
TC ?=
CONCURRENCY ?=
PAIRS ?=
SPRT ?=
TIME ?=
OPENINGS ?=
MOVETIME ?= 10000
GAMES ?=
MOVETIME_TT ?=
PLIES ?=
TT_EXPONENT ?=
GUI_PORT ?=
GUI_BIND ?=
GUI_TUNNEL ?=
SYZYGY_PATH ?= $(HOME)/syzygy-nr
SYZYGY_RANDOM ?=
TOOL_TARGETS := tools/perft tools/bench tools/speed_compare tools/match tools/make_openings tools/make_ccrl_openings tools/make_endgames tools/gui_match tools/tt_stats tools/syzygy_reference tools/tb_suite tools/tb_trade_suite tools/nne_data tools/tune_data tools/tune tools/wdl_fit tools/tempo_swing tools/gaviota_reference tools/mate_suite tools/ptt_seed tools/watch_tt
PROFILE_CXXFLAGS ?= -O2 -mpopcnt -g -pg -Wall -Wno-unknown-pragmas -Wno-parentheses -Wno-unused-variable

.PHONY: all run play asm tests debug profile-startpos perft bench speed-compare match gui-match gui tt-stats tempo-swing syzygy-test gaviota-test nne-test nne-retrain tb-suite tb-trade-suite mate-suite ptt-seed clean rebuild

all: $(TARGET) $(UCI_TARGET)

$(TARGET): $(MAIN) $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $@ $(MAIN)

# The default weight set (#85), compiled in as text (lib/weight_set.hpp). A new default
# is a new weights/wN.txt named here. The header is committed, so a plain g++ line builds.
WEIGHTS_DEFAULT := weights/w6.txt
lib/weights_default.hpp: $(WEIGHTS_DEFAULT)
	{ printf '// OWNERSHIP=Claude\n// Generated by make from %s: edit that file, not this one (#85).\n' $<; \
	  printf '#ifndef WEIGHTS_DEFAULT_HPP\n#define WEIGHTS_DEFAULT_HPP\n'; \
	  printf 'static const char WEIGHTS_DEFAULT_FILE[] = "%s";\n' $<; \
	  printf 'static const char WEIGHTS_DEFAULT_TEXT[] = R"WEIGHTS(\n'; cat $<; \
	  printf ')WEIGHTS";\n#endif // WEIGHTS_DEFAULT_HPP\n'; } > $@

# Gaviota DTM prober (#77): third-party C (third_party/README.md), built with gcc
# into libgtb.a and linked into the UCI engines only. Every other build sees
# lib/gaviota.hpp's "no tables" stubs.
GTB_DIR := third_party/gaviota
GTB_SOURCES := $(shell find $(GTB_DIR) -name '*.c')
GTB_OBJECTS := $(patsubst $(GTB_DIR)/%.c,$(GTB_DIR)/obj/%.o,$(GTB_SOURCES))
GTB_CFLAGS := -O2 -DNDEBUG -DZ_PREFIX -w $(addprefix -I$(GTB_DIR)/,sysport compression compression/liblzf compression/zlib compression/lzma compression/huffman)
GTB_LIB := $(GTB_DIR)/libgtb.a
WITH_GTB := -DWITH_GAVIOTA $(GTB_LIB)
# The commit the UCI engines report as provenance (#79, lib/engine_version.hpp).
ENGINE_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null)$(shell git diff --quiet HEAD 2>/dev/null || echo -dirty)
WITH_COMMIT := -DENGINE_COMMIT='"$(ENGINE_COMMIT)"'

$(GTB_DIR)/obj/%.o: $(GTB_DIR)/%.c
	@mkdir -p $(@D)
	$(CC) $(GTB_CFLAGS) -c -o $@ $<

$(GTB_LIB): $(GTB_OBJECTS)
	$(AR) rcs $@ $^

# UCI engine (stdin/stdout protocol), separate binary so GUIs can launch it without arguments
$(UCI_TARGET): ascaniusfish_uci.cpp $(HEADERS) $(SOURCES) $(GTB_LIB)
	$(CXX) $(CXXFLAGS) -pthread -o $@ ascaniusfish_uci.cpp $(WITH_COMMIT) $(WITH_GTB)

# The same engine with -DTT_BOUNDS_NEVER_NARROW=0 (#65): UCI TTNarrowing/TTNarrowingDeeper
# switch narrowing on stored bounds back on. make gui NARROW=1 drives it.
UCI_NARROW_TARGET := ascaniusfish_uci_narrow
$(UCI_NARROW_TARGET): ascaniusfish_uci.cpp $(HEADERS) $(SOURCES) $(GTB_LIB)
	$(CXX) $(CXXFLAGS) -DTT_BOUNDS_NEVER_NARROW=0 -pthread -o $@ ascaniusfish_uci.cpp $(WITH_COMMIT) $(WITH_GTB)

a.out: $(MAIN) $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $@ $(MAIN)

asm: ascaniusfish.s

ascaniusfish.s: $(MAIN) $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -S -o $@ $(MAIN)

tests: $(TEST_TARGETS)

hash_table_test: hash_table_test.cpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $@ hash_table_test.cpp

hash_game_test: hash_game_test.cpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $@ hash_game_test.cpp

pv_first_move_diagnostic: pv_first_move_diagnostic.cpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $@ pv_first_move_diagnostic.cpp

benchmarks/profile_startpos: benchmarks/profile_startpos.cpp $(HEADERS) $(SOURCES)
	$(CXX) $(PROFILE_CXXFLAGS) -o $@ benchmarks/profile_startpos.cpp

profile-startpos: benchmarks/profile_startpos
	cd benchmarks && ./profile_startpos $(PROFILE_ITERATIONS) $(PROFILE_DEPTH)
	cd benchmarks && gprof ./profile_startpos gmon.out > profile_startpos.gprof
	@echo "Wrote benchmarks/profile_startpos.gprof"

tools/perft: tools/perft.cpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/perft.cpp

tools/bench: tools/bench.cpp tools/bench_positions.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/bench.cpp

tools/speed_compare: tools/speed_compare.cpp tools/git_build.hpp
	$(CXX) -O2 -Wall -o $@ tools/speed_compare.cpp

tools/match: tools/match.cpp tools/game_rules.hpp tools/git_build.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/match.cpp

tools/gui_match: tools/gui_match.cpp tools/game_rules.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/gui_match.cpp

tools/make_openings: tools/make_openings.cpp tools/game_rules.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/make_openings.cpp

# The SPRT's opening suite from CCRL games (#92): no search, so the TT is minimal.
tools/make_ccrl_openings: tools/make_ccrl_openings.cpp tools/game_rules.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -DTT_EXPONENT=10 -o $@ tools/make_ccrl_openings.cpp

tools/make_endgames: tools/make_endgames.cpp tools/game_rules.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/make_endgames.cpp

# The labels' TT (a fresh one per position, like ucinewgame): small, since
# several labellers run at once (#50).
NNE_TT ?= 16
tools/nne_data: tools/nne_data.cpp gui/move_tree.hpp tools/game_rules.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -DTT_EXPONENT=$(NNE_TT) -pthread -o $@ tools/nne_data.cpp

# The tuner's position set from the CCRL archive (#86): no search, so the TT is minimal.
tools/tune_data: tools/tune_data.cpp gui/move_tree.hpp tools/game_rules.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -DTT_EXPONENT=10 -pthread -o $@ tools/tune_data.cpp

# The weight tuner (#87): static eval only, no search.
tools/tune: tools/tune.cpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) $(WITH_COMMIT) -DTT_EXPONENT=10 -pthread -o $@ tools/tune.cpp

# Stockfish's win/draw/loss curve fitted to tools/match PGN (#54).
tools/wdl_fit: tools/wdl_fit.cpp
	$(CXX) -O2 -std=c++17 -Wall -o $@ tools/wdl_fit.cpp

# The eval-correction net's trainer (#51), against the libtorch inside the
# installed torch wheel. Not part of any other target: compiling it peaks at
# 1.25 GB, so build it alone, never next to an engine build.
TORCH ?= $(HOME)/.local/lib/python3.10/site-packages/torch
tools/nne_train: tools/nne_train.cpp
	$(CXX) -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=1 -Wall -Wno-unused-variable \
	  -I$(TORCH)/include -I$(TORCH)/include/torch/csrc/api/include -o $@ tools/nne_train.cpp \
	  -L$(TORCH)/lib -Wl,-rpath,$(TORCH)/lib -Wl,--no-as-needed \
	  -ltorch -ltorch_cpu -ltorch_cuda -lc10 -lc10_cuda

tools/syzygy_reference: tools/syzygy_reference.cpp tools/syzygy_positions.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/syzygy_reference.cpp

tools/tb_suite: tools/tb_suite.cpp tools/syzygy_positions.hpp tools/game_rules.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/tb_suite.cpp

# Endgame games with the tablebases (issue #38): the engine has to win what is
# won inside the 50-move rule and not lose what is drawn. TB_MOVETIME in ms.
# With the Gaviota DTM tables (#77; on when $(GAVIOTA_PATH) exists, GAVIOTA=<dir>
# picks another, GAVIOTA=none turns them off) every won game must also report a
# shrinking mate N; TB_SUITE_ARGS=opp_gaviota=on makes it shrink by exactly one.
TB_MOVETIME ?=
GAVIOTA_PATH ?= $(HOME)/gaviota
GAVIOTA ?= $(wildcard $(GAVIOTA_PATH))
TB_SUITE_ARGS ?=
tb-suite: $(UCI_TARGET) tools/tb_suite
	./tools/tb_suite run $(SYZYGY_PATH) movetime=$(TB_MOVETIME) $(if $(filter-out none,$(GAVIOTA)),gaviota=$(GAVIOTA)) $(TB_SUITE_ARGS)

tools/mate_suite: tools/mate_suite.cpp tools/game_rules.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/mate_suite.cpp

# Forced mates (issue #78): Lichess mate puzzles, one `go movetime` each; the
# hit rate per N, where a hit is `mate N` with N the shortest mate.
MATE_MOVETIME ?= 1000
MATE_SUITE_ARGS ?=
mate-suite: $(UCI_TARGET) tools/mate_suite
	./tools/mate_suite run movetime=$(MATE_MOVETIME) $(MATE_SUITE_ARGS)

# Seeded vs cold search to the stored depth + 1 (#79): does the PTT's line help?
tools/ptt_seed: tools/ptt_seed.cpp tools/bench_positions.hpp tools/uci_engine.hpp
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/ptt_seed.cpp

PTT_SEED_ARGS ?=
ptt-seed: $(UCI_TARGET) tools/ptt_seed
	./tools/ptt_seed $(PTT_SEED_ARGS)

# Fixed-depth Watch, one shared process vs one per side (#91): time per move.
tools/watch_tt: tools/watch_tt.cpp tools/game_rules.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/watch_tt.cpp

tools/tb_trade_suite: tools/tb_trade_suite.cpp tools/syzygy_positions.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/tb_trade_suite.cpp

# The static eval's tempo bias from the odd/even swing of the root score (#70):
# median per phase bin and depth, net off. TEMPO_ARGS e.g. engine=<ref|binary> per_bin=900.
TEMPO_ARGS ?=
tools/tempo_swing: tools/tempo_swing.cpp tools/git_build.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ tools/tempo_swing.cpp

tempo-swing: tools/tempo_swing
	./tools/tempo_swing $(TEMPO_ARGS)

# 6-7 piece positions where the right trade decides the result (issue #39): the
# solve count with the tables (TB_TRADE_ARGS=tables=off for the baseline).
TB_TRADE_ARGS ?=
tb-trade-suite: $(UCI_TARGET) tools/tb_trade_suite
	./tools/tb_trade_suite run $(SYZYGY_PATH) $(TB_TRADE_ARGS)

# Browser GUI server (issues #14-#17). Plain g++, no Node: gui/web/vendor holds
# a prebuilt chessground bundle, and the HTTP/SSE server is gui/http_server.hpp.
GUI_TARGET := gui/ascaniusfish_gui
GUI_HEADERS := gui/http_server.hpp gui/session.hpp gui/move_tree.hpp gui/json.hpp gui/engine_link.hpp gui/analysis_store.hpp gui/tablebase_view.hpp gui/ptt.hpp

$(GUI_TARGET): gui/gui_server.cpp $(GUI_HEADERS) tools/game_rules.hpp tools/uci_engine.hpp $(HEADERS) $(SOURCES) $(GTB_LIB)
	$(CXX) $(CXXFLAGS) -pthread -o $@ gui/gui_server.cpp $(WITH_GTB)

# Syzygy prober (lib/syzygy.hpp) vs the recorded Lichess reference, plus a
# consistency check over SYZYGY_RANDOM (300) random positions per table
diagnostics/syzygy_test: diagnostics/syzygy_test.cpp tools/syzygy_positions.hpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ diagnostics/syzygy_test.cpp

syzygy-test: diagnostics/syzygy_test
	./diagnostics/syzygy_test $(SYZYGY_PATH) $(SYZYGY_RANDOM)

# Gaviota DTM probe (lib/gaviota.hpp, #77) vs Lichess's DTM (tools/gaviota_reference.txt)
# and against its own children
diagnostics/gaviota_test: diagnostics/gaviota_test.cpp $(HEADERS) $(SOURCES) $(GTB_LIB)
	$(CXX) $(CXXFLAGS) -pthread -o $@ diagnostics/gaviota_test.cpp $(WITH_GTB)

gaviota-test: diagnostics/gaviota_test
	./diagnostics/gaviota_test $(GAVIOTA_PATH)

tools/gaviota_reference: tools/gaviota_reference.cpp
	$(CXX) -O2 -Wall -o $@ tools/gaviota_reference.cpp

# The engine's eval-correction net (lib/nne.hpp) vs the trainer's test-set
# predictions: every correction within 0.01 cp (#52)
diagnostics/nne_inference_test: diagnostics/nne_inference_test.cpp $(HEADERS) $(SOURCES)
	$(CXX) $(CXXFLAGS) -pthread -o $@ diagnostics/nne_inference_test.cpp

nne-test: diagnostics/nne_inference_test
	./diagnostics/nne_inference_test

# After a change to eval(): relabel the dataset's positions, retrain the net
# and run nne-test's check on it (#56, docs/NNE_RELABEL.md). FROM=<branch>
# takes a cloud session's labels; MINUTES=M stops the relabel after M minutes
# (run again to carry on).
nne-retrain:
	tools/nne_retrain.sh $(if $(FROM),from=$(FROM)) $(if $(MINUTES),minutes=$(MINUTES)) $(if $(JOBS),jobs=$(JOBS))

# Move generation vs known perft counts (PERFT_DEPTH=4 for a quick check)
perft: tools/perft
	./tools/perft $(PERFT_DEPTH)

# Fixed-depth search; total nodes = search signature (BENCH_DEPTH overrides)
bench: tools/bench
	./tools/bench $(BENCH_DEPTH) $(if $(NNE),nne=$(NNE))

# Speed A/B of two git refs ("." = working tree): make speed-compare A=main B=.
speed-compare: tools/speed_compare
	@test -n "$(A)" -a -n "$(B)" || (echo "usage: make speed-compare A=<ref> B=<ref> [ROUNDS=10] [BENCH_DEPTH=n]"; exit 2)
	./tools/speed_compare $(A) $(B) $(ROUNDS) $(BENCH_DEPTH)

# Elo match of two engines (git refs or UCI binaries): make match A=main B=.
match: tools/match
	@test -n "$(A)" -a -n "$(B)" || (echo "usage: make match A=<ref|binary> B=<ref|binary> [DEPTH=3] [TC=10+0.1] [CONCURRENCY=n] [PAIRS=n] [SPRT=0,10] [TIME=10] [OPENINGS=file] [OPTIONS_A=Name=Value,...] [OPTIONS_B=...]"; exit 2)
	./tools/match $(A) $(B) depth=$(DEPTH) tc=$(TC) concurrency=$(CONCURRENCY) pairs=$(PAIRS) sprt=$(SPRT) time=$(TIME) openings=$(OPENINGS) optionsA="$(OPTIONS_A)" optionsB="$(OPTIONS_B)"

# One game of two UCI binaries at MOVETIME ms per move, shown in display_board.py
gui-match: tools/gui_match
	@test -n "$(A)" -a -n "$(B)" || (echo "usage: make gui-match A=<white binary> B=<black binary> [MOVETIME=10000]"; exit 2)
	./tools/gui_match $(A) $(B) movetime=$(MOVETIME)

# The board in the browser: prints a http://localhost:<port> URL and serves it.
# Tablebases are on by default when $(SYZYGY_PATH) exists; SYZYGY=<dir> picks another, SYZYGY=none turns them off.
SYZYGY ?= $(wildcard $(SYZYGY_PATH))
# The Gaviota DTM tables (#77) likewise through GAVIOTA (see tb-suite).
# Play mode drives $(UCI_TARGET) over pipes, so that has to exist too; NARROW=1 drives
# $(UCI_NARROW_TARGET) instead, whose narrowing the gear then switches (#65).
gui: $(GUI_TARGET) $(if $(NARROW),$(UCI_NARROW_TARGET),$(UCI_TARGET))
	./$(GUI_TARGET) $(if $(NARROW),engine=./$(UCI_NARROW_TARGET)) $(if $(GUI_PORT),port=$(GUI_PORT)) $(if $(GUI_BIND),bind=$(GUI_BIND)) $(if $(GUI_TUNNEL),tunnel=$(GUI_TUNNEL)) $(if $(filter-out none,$(SYZYGY)),syzygy=$(SYZYGY)) $(if $(filter-out none,$(GAVIOTA)),gaviota=$(GAVIOTA))

# make gui plus a cloudflared quick tunnel, so the printed link is already
# shareable — no separate terminal, no combining a token by hand (issue #27).
gui-remote: $(GUI_TARGET) $(UCI_TARGET)
	./$(GUI_TARGET) $(if $(GUI_PORT),port=$(GUI_PORT)) tunnel=cloudflared

# TT discard statistics over self-play games (issue #11). The only build with
# -DTT_STATS; rebuilt every time so TT_EXPONENT=n always takes effect.
tt-stats:
	$(CXX) $(CXXFLAGS) -DTT_STATS $(if $(TT_EXPONENT),-DTT_EXPONENT=$(TT_EXPONENT)) -pthread -o tools/tt_stats tools/tt_stats.cpp
	./tools/tt_stats depth=$(DEPTH) movetime=$(MOVETIME_TT) games=$(GAMES) plies=$(PLIES)

run play: $(TARGET)
	./$(TARGET)

debug: CXXFLAGS := -O0 -mpopcnt -g -Wall -Wno-unknown-pragmas -Wno-parentheses -Wno-unused-variable
debug: $(TARGET)

rebuild: clean all

clean:
	rm -rf $(GTB_DIR)/obj $(GTB_LIB)
	rm -f $(TARGET) $(UCI_TARGET) $(UCI_NARROW_TARGET) a.out ascaniusfish.s $(TEST_TARGETS) $(TOOL_TARGETS) diagnostics/syzygy_test diagnostics/gaviota_test diagnostics/nne_inference_test tools/nne_train $(GUI_TARGET) benchmarks/profile_startpos benchmarks/gmon.out benchmarks/profile_startpos.gprof
