// OWNERSHIP=Claude
// Generated by make from weights/w5.txt: edit that file, not this one (#85).
#ifndef WEIGHTS_DEFAULT_HPP
#define WEIGHTS_DEFAULT_HPP
static const char WEIGHTS_DEFAULT_FILE[] = "weights/w5.txt";
static const char WEIGHTS_DEFAULT_TEXT[] = R"WEIGHTS(
# OWNERSHIP=Claude
# A weight set of Ascaniusfish's eval: every number basic_eval() uses (#85).
# Format: lib/weight_set.hpp.
version 5
parent 4
data -
tuner -
loss -

# material_eval(): pawn rook knight bishop queen king, with all pieces on (game_phase() 24) and with none
piece_value 140 858 468 579 1642 379
piece_value_endgame 136 829 452 559 1586 379

# piecetable(): rank 8 first, files a..h, white's view; black reads it rank-flipped
piece_table_value_opening pawn
   70   70   70   70   70   70   70   70
   73   93   99   94   95   72   70   57
   39   72   49   54   97  131  131    6
   -7   29   17   10   89   93   43    4
  -20  -23   -2   -6   58   38   38    0
  -44  -66  -61  -31  -19   20   -9  -11
  -41  -96  -64  -86  -54  -18  -31  -73
    0    0    0    0    0    0    0    0
piece_table_value_opening rook
   62   75   75   81   71   58   67   69
   27   24   61   71   63   64   55   66
   15   32   33   52   84   63   69   48
   -8    8   36   51   74   56   67   47
  -59  -23   -4   13   23   -2   23  -15
  -66  -43  -36  -16   21  -16   35    9
  -86  -56  -28  -33  -17    7   22  -21
  -74  -46  -40  -24  -12  -29   26  -41
piece_table_value_opening knight
  -45   24   40   61   67   43   20  -14
   10   38   59   95   98   79   45   32
   27    6   74   94  124  102   96   41
   48   21   60   75   30   99  123  114
    2   55   46   55   86   64  115   84
    3    5  -27   64   83   25   83   71
  -40   -3   15   41   28   56   42   44
  -19   -6   -6   15   38   37   12  -11
piece_table_value_opening bishop
    3   11   27   33   27   18   15    4
   -4   27   25   46   50   41   17   13
   11   20   18   46   73   96   80   62
   -5   58   25   78   56   90   81   40
   17   24   46   61   67   21   80   55
    9   27   22   38    7   38    9   58
   31    1   51   -4   34   -4   33  -22
   20   53   14   -5   -3   27    9  -32
piece_table_value_opening queen
   17   52   55   64   69   55   53   58
   -1  -31   12   37   51   45   31   91
   -7   -2  -11   12   49   64   67   94
   -8  -34  -13   -8   17   37   69   79
    0  -31  -29   -7    1   16   65   95
   -9  -11   -8  -18   -8   24   40   87
   22   18   18   32   33   23   18   46
   48   37   44   81   58  -15  -13   34
piece_table_value_opening king
    1  -16  -36  -56  -58  -36  -16    0
   -5  -18  -37  -61  -62  -41  -20   -7
   -8  -21  -34  -59  -62  -36  -24   -6
  -14  -24  -41  -64  -64  -41  -30  -13
  -19  -28  -42  -68  -69  -49  -33  -51
  -12  -28  -49  -81  -73  -76  -67  -68
   43  -29  -45  -87  -72 -106  -30  -41
  -57  -46  -21 -119  -39 -154  -50  -40
piece_table_value_endgame pawn
  122  122  122  122  122  122  122  122
   73   93  107   92  109   98   99   80
   94   85   80   59   66   98  109  113
   94   65   47    9    7   36   79   86
   67   65   31    9   14   46   54   40
   40   44   45   45   47   49   44   24
   34   64   57   23   62   92   79   26
    0    0    0    0    0    0    0    0
piece_table_value_endgame rook
   57   64   65   53   50   48   58   53
   78   80   58   66   54   54   59   56
   80   69   63   63   57   54   54   57
   70   77   62   61   63   55   61   52
   38   35   47   38   37   34   35   10
   -7   -2   -3    1  -14  -13  -12  -13
  -17  -16  -25  -27  -35  -62  -41  -38
  -53  -27  -13  -33  -43  -62  -42  -44
piece_table_value_endgame knight
  -21   17   21   33   39   24    8  -11
   16   26   34   53   49   30   24   21
   27   45   14   27   35   36   33   29
   34   27   31   53   62   46   51   51
   21   27   17    9   20   31   39   31
  -18   -3  -24    3  -22  -39    3   10
  -10    0  -23  -27  -21  -13    6    1
   -9  -37  -12   -7  -17  -28  -21   -6
piece_table_value_endgame bishop
   17   18   35   29   23   16   17    7
    3   24   21   25   25   25   17    8
   13   28   26   13   24   29   34   27
   13    9    7   15   15   26   13   17
   13    4   11   -4    4   15    9  -10
   11   13   -1  -12   -1   -9   -8    0
    3  -33  -31  -24  -34   -8  -33  -28
   -3  -12  -61  -18  -14  -36   -4  -12
piece_table_value_endgame queen
   29   46   48   49   54   45   45   46
   29   30   39   36   43   38   32   57
   21   34   29   33   48   48   49   50
   29   25   33   21   35   41   49   57
   13   17   10   13    4   32   36   46
    3   -6  -12  -21   -8  -13    4   12
   -6  -19  -60  -63  -66  -64  -53    4
    2  -22  -25  -69  -57  -58  -19   16
piece_table_value_endgame king
    2   20   40   59   54   39   19   -1
   23   52   75   81   78   68   49   21
   38   68  101  103  101   89   67   36
   41   71   97  107   97   93   66   50
   31   59   87   87   83   68   48   12
   10   28   47   50   43   33    0  -22
   -7   -1    7   17    0    6  -36  -41
  -48  -15  -18   -3  -63  -24  -74 -120

# positional_eval()
punishment_for_double_pawn 22
punishment_for_trippled_pawn 36
punishment_for_isolated_pawn 11

# passed_pawn_eval(): by relative rank, with no pieces on and with all of them
passed_pawn_value 0 21 21 29 79 122 175 0
passed_pawn_value_opening 0 11 11 15 40 61 88 0

# passed_pawn_eval()'s endgame modifiers (#90), by relative rank where 8 numbers, scaled to 0 with all pieces on:
# nothing ahead; per square (max 5) of the enemy king's / our king's distance to the stop square;
# an own pawn beside or protecting it; our rook behind it (+), theirs (-); unstoppable by the
# rule of the square (not scaled, the side's best passer only)
passed_free_path 0 7 -7 2 6 31 78 0
passed_king_enemy 0 8 5 23 48 74 81 0
passed_king_own 0 14 17 24 39 43 40 0
passed_supported 0 -14 33 55 82 130 49 0
passed_rook_behind 54
passed_unstoppable 7

# piece_activity_eval(): added for the owner per piece hit
activity_pawn_attack 73
activity_pawn_defend 6
activity_pawn_blocked -36
activity_pawn_push_attack 22
activity_pawn_push_defend -15
activity_bishop_defend 17
activity_bishop_attack -3
activity_rook_defend 20
activity_rook_attack 18
activity_queen_defend 18
activity_queen_attack 8
activity_knight_defend 23
activity_knight_attack 3
activity_king_defend 8
activity_king_attack 38

# piece_activity_eval()'s mobility: by the number of squares the piece attacks that no own piece
# stands on (0, 1, ...), with all pieces on and with none
mobility_knight_opening 0 25 50 75 100 125 150 175 200
mobility_knight_endgame 0 25 50 75 100 125 150 175 200
mobility_bishop_opening 0 16 31 47 62 78 93 109 124 140 155 171 186 202
mobility_bishop_endgame 0 16 31 47 62 78 93 109 124 140 155 171 186 202
mobility_rook_opening 0 15 30 45 60 75 90 105 120 135 150 165 180 195 210
mobility_rook_endgame 0 15 30 45 60 75 90 105 120 135 150 165 180 195 210
mobility_queen_opening 0 15 31 46 61 76 92 107 122 137 153 168 183 198 214 229 244 259 275 290 305 320 336 351 366 381 397 412
mobility_queen_endgame 0 15 31 46 61 76 92 107 122 137 153 168 183 198 214 229 244 259 275 290 305 320 336 351 366 381 397 412

# pawn_shape_eval() (#90), added for the owner, with all pieces on and with none: a backward pawn
# (own pawns on a neighbouring file, all ahead of it, its stop square attacked by an enemy pawn);
# two own pawns side by side, by relative rank
pawn_backward_opening 0
pawn_backward_endgame 0
pawn_phalanx_opening 0 0 0 0 0 0 0 0
pawn_phalanx_endgame 0 0 0 0 0 0 0 0

# placement_eval() (#90), added for the owner, with all pieces on and with none: the bishop pair;
# a rook on a file without pawns, without own pawns; a rook on the 7th with enemy pawns there or
# the enemy king on the 8th; a knight or bishop on ranks 4-6, protected by a pawn, that no enemy
# pawn can attack
bishop_pair_opening 0
bishop_pair_endgame 0
rook_open_file_opening 0
rook_open_file_endgame 0
rook_semi_open_file_opening 0
rook_semi_open_file_endgame 0
rook_seventh_opening 0
rook_seventh_endgame 0
outpost_knight_opening 0
outpost_knight_endgame 0
outpost_bishop_opening 0
outpost_bishop_endgame 0

# threat_eval() (#90), added for the attacker: per enemy piece attacked by a pawn, a knight or
# bishop, a rook, by its type (pawn rook knight bishop queen); per enemy piece but the king
# attacked and not defended
threat_by_pawn 0 0 0 0 0
threat_by_minor 0 0 0 0 0
threat_by_rook 0 0 0 0 0
threat_hanging 0

# tempo_eval(): the side to move's, with all and with no pieces on
tempo_opening -6
tempo_endgame 5

# king_safety_eval() (src/king_safety.cpp); by piece: pawn rook knight bishop queen king
ks_attacker_weight 0 69 83 58 -17 0
ks_min_attackers 2
ks_hit 37
ks_weak_ring_square 91
ks_safe_check 0 809 644 571 672 0
ks_unsafe_check 207
ks_no_queen 981
ks_danger_div 5000
ks_shelter 125 40 48 71 84 74 15 16
ks_open_file 55
ks_storm 8 0 -28 51 74 15 -22 -16
ks_storm_blocked_div 4
ks_full_piece_material 12
# set 4 converted to eval version 4's terms (game phase, mobility tables, no halving; mobility_value spread at 0.5, see the commit that made set 5), not refitted: mean |diff| 15.9 cp to set 4 under eval version 3 on 50000 test positions
)WEIGHTS";
#endif // WEIGHTS_DEFAULT_HPP
