// OWNERSHIP=Claude
// Generated by make from weights/w7.txt: edit that file, not this one (#85).
#ifndef WEIGHTS_DEFAULT_HPP
#define WEIGHTS_DEFAULT_HPP
static const char WEIGHTS_DEFAULT_FILE[] = "weights/w7.txt";
static const char WEIGHTS_DEFAULT_TEXT[] = R"WEIGHTS(
# OWNERSHIP=Claude
# A weight set of Ascaniusfish's eval: every number basic_eval() uses (#85).
# Format: lib/weight_set.hpp.
version 7
parent 6
data ccrl-cegt-tcec-3000-balanced
tuner 0411135
loss 0.113938

# material_eval(): pawn rook knight bishop queen king, with all pieces on (game_phase() 24) and with none
piece_value 140 408 267 342 1313 379
piece_value_endgame 220 1334 724 796 2284 379

# piecetable(): rank 8 first, files a..h, white's view; black reads it rank-flipped
piece_table_value_opening pawn
   70   70   70   70   70   70   70   70
   78  104  121  118  120   74   68   20
   18   49   47   49   99  114  121  -39
  -28  -17  -12  -20   39   48   -8  -38
  -43  -60  -45  -49    4    2  -10  -29
  -72 -103  -88  -65  -48   -7  -40  -43
  -57  -96  -80 -125  -66  -23  -24  -89
    0    0    0    0    0    0    0    0
piece_table_value_opening rook
   54   74   85   77   79   75  102  125
   16    8   55   78   69   81   94  112
  -18    7    8   32   99  110  130   82
  -36   -3    9   45   71   90  116   76
  -91  -59  -46  -15   11  -12   40  -17
  -97  -81  -83  -42   -3  -19   25    9
 -105  -90  -73  -62  -39  -16   22  -32
  -92  -77  -81  -64  -47  -53   -1  -65
piece_table_value_opening knight
 -129   23   34   58   74   46   20  -43
    1   32   47   97  119  107   79   70
   28  -20   77   70  147  145  125   64
   43   18   56   70   59  112  129  136
   -3   55   32   40   71   61  129   75
   -5   -9  -33   35   58   18   67   81
  -53  -11   -5   16    8   45   49   64
  -54   -2  -43   -5   28   39   20  -21
piece_table_value_opening bishop
    5   -6   25   21   21    3   18  -14
  -36   11    7   39   29   34   -2   14
   17   -1    0   22   91  139  121   66
    5   32    8   61   34  112   52   57
    8   12   38   26   41   13   86   52
    2   25   10   18   -1   29   23   69
   42    4   43   -9   20  -11   38   -1
   46   75   10   -6    0   27   27  -20
piece_table_value_opening queen
   15   67   72   81  100   93  102  114
  -35  -55    0   47   65   68   53  133
  -18  -20  -10   12   73  123  124  105
  -13  -27  -17    7   41   58  110   76
  -20  -44  -22   -8    8   23   76   70
  -40  -30  -23  -28  -20   19   28   68
  -23  -11  -16   -6   -3    2    6   11
    0  -10   -8    5   16  -53  -76   -8
piece_table_value_opening king
    1  -12  -28  -53  -55  -31  -10   -3
   -3   -5  -21  -48  -50  -26   -4    0
   -8  -11  -22  -49  -49  -17  -13    1
  -18  -20  -42  -62  -61  -35  -39  -26
  -25  -26  -44  -77  -86  -68  -55 -113
   -1  -15  -54  -92  -92 -110  -88  -99
   90  -15  -32  -89  -81 -115  -25  -38
  -38  -43  -37 -143  -44 -152  -55  -35
piece_table_value_endgame pawn
  122  122  122  122  122  122  122  122
   76   98  101   86  110  106  132   89
  114  108   81   68   71  118  132  141
   89   68   36    8    6   18   68   67
   69   67   30   10   16   29   44   20
   50   55   41   51   46   33   31   12
   54   71   49   75   77   68   59   16
    0    0    0    0    0    0    0    0
piece_table_value_endgame rook
   86   88   82   67   71   83   98   76
   72   82   57   55   59   59   73   53
  115  103   99   79   70   78   79   78
   94   94   76   62   59   62   71   61
   63   56   50   25   24   43   38   15
    3    5   -2  -21  -46  -35  -37  -36
   -5   -9  -23  -38  -55  -80  -87  -65
   -7   -4    3  -21  -32  -32  -38   -8
piece_table_value_endgame knight
  -60   36   37   45   66   42   19  -42
   33   49   39   61   60   27   51   46
   39   58    8   40   22   41   31   52
   51   21   31   63   54   46   58   60
   31   24   31   25   34   31   37   32
  -21   -3  -13    4   -5  -42    1   14
    0    5  -36  -11  -20  -25    8   -4
  -29  -27  -11   -7  -22  -37  -25  -12
piece_table_value_endgame bishop
   42   36   50   45   36   24   27   14
   16   40   32   34   28   44   37   20
   31   39   30    9   23   24   44   43
   20   15    7   29   23   16   25   20
   19    4   13   15   22    8   -8  -28
   18    5    0   -1    1  -14  -30  -10
    3  -25  -36  -21  -32  -17  -37  -60
   -3  -35  -27  -20  -18  -17  -14  -30
piece_table_value_endgame queen
   54   79   81   81   93   96   97   93
   77  102  105   95   91   88   88  110
   58   91   87   99  110  106   99   96
   73   73   82   63   95   92  107  118
   18   42   18   25    9   37   37   71
   -2  -34  -19  -45  -24  -46  -37  -21
  -38  -58  -97  -81  -90 -159 -147  -35
  -45  -87  -80  -92 -140 -147  -72   -6
piece_table_value_endgame king
   -5   39   62   72   62   57   37  -11
   33   96  122  116  111  128  108   39
   49  115  146  131  135  139  118   55
   51   82  108  109   97   96   73   41
   26   49   74   72   66   51   32   -3
  -26    6   34   36   28   17  -13  -40
  -72  -27  -12    5  -10   -9  -59  -75
 -119  -57  -38  -24  -78  -43  -95 -161

# positional_eval()
punishment_for_double_pawn 26
punishment_for_trippled_pawn 69
punishment_for_isolated_pawn 16

# passed_pawn_eval(): by relative rank, with no pieces on and with all of them
passed_pawn_value 0 114 102 114 128 123 221 0
passed_pawn_value_opening 0 5 -19 -24 20 45 138 0

# passed_pawn_eval()'s endgame modifiers (#90), by relative rank where 8 numbers, scaled to 0 with all pieces on:
# nothing ahead; per square (max 5) of the enemy king's / our king's distance to the stop square;
# an own pawn beside or protecting it; our rook behind it (+), theirs (-); unstoppable by the
# rule of the square (not scaled, the side's best passer only)
passed_free_path 0 22 0 7 24 72 168 0
passed_king_enemy 0 -15 -10 16 45 78 81 0
passed_king_own 0 20 22 35 47 55 61 0
passed_supported 0 -1 29 41 74 187 177 0
passed_rook_behind 81
passed_unstoppable 48

# piece_activity_eval(): added for the owner per piece hit
activity_pawn_attack 77
activity_pawn_defend 2
activity_pawn_blocked -27
activity_pawn_push_attack 16
activity_pawn_push_defend -21
activity_bishop_defend 22
activity_bishop_attack -10
activity_rook_defend 23
activity_rook_attack 28
activity_queen_defend 13
activity_queen_attack -6
activity_knight_defend 24
activity_knight_attack -3
activity_king_defend 9
activity_king_attack 39

# piece_activity_eval()'s mobility: by the number of squares the piece attacks that no own piece
# stands on (0, 1, ...), with all pieces on and with none
mobility_knight_opening -37 -17 28 62 90 107 131 153 179
mobility_knight_endgame -12 24 84 115 141 178 195 220 225
mobility_bishop_opening -34 -5 15 25 46 68 80 94 103 123 129 155 160 221
mobility_bishop_endgame -48 -65 -12 35 90 128 153 173 188 198 203 203 212 192
mobility_rook_opening 9 25 41 49 47 56 63 72 79 86 91 98 114 140 157
mobility_rook_endgame -8 48 54 65 93 114 132 153 176 195 206 211 214 215 212
mobility_queen_opening 15 92 107 114 117 121 128 137 141 148 157 155 158 166 163 169 169 184 193 215 221 256 287 319 345 364 391 409
mobility_queen_endgame 0 17 26 41 45 78 95 108 138 156 184 217 242 260 292 313 334 344 350 354 361 338 347 337 341 356 384 405

# pawn_shape_eval() (#90), added for the owner, with all pieces on and with none: a backward pawn
# (own pawns on a neighbouring file, all ahead of it, its stop square attacked by an enemy pawn);
# two own pawns side by side, by relative rank
pawn_backward_opening -28
pawn_backward_endgame -27
pawn_phalanx_opening 0 -31 11 38 80 69 13 0
pawn_phalanx_endgame 0 -21 -5 26 113 47 29 0

# placement_eval() (#90), added for the owner, with all pieces on and with none: the bishop pair;
# a rook on a file without pawns, without own pawns; a rook on the 7th with enemy pawns there or
# the enemy king on the 8th; a knight or bishop on ranks 4-6, protected by a pawn, that no enemy
# pawn can attack
bishop_pair_opening 7
bishop_pair_endgame 168
rook_open_file_opening 61
rook_open_file_endgame 27
rook_semi_open_file_opening 31
rook_semi_open_file_endgame 27
rook_seventh_opening -51
rook_seventh_endgame 69
outpost_knight_opening 25
outpost_knight_endgame 36
outpost_bishop_opening 30
outpost_bishop_endgame 4

# threat_eval() (#90), added for the attacker: per enemy piece attacked by a pawn, a knight or
# bishop, a rook, by its type (pawn rook knight bishop queen); per enemy piece but the king
# attacked and not defended
threat_by_pawn -25 20 7 -12 -15
threat_by_minor -3 81 75 62 66
threat_by_rook -31 -13 9 15 50
threat_hanging 26

# tempo_eval(): the side to move's, with all and with no pieces on
tempo_opening 13
tempo_endgame 16

# king_safety_eval() (src/king_safety.cpp); by piece: pawn rook knight bishop queen king
ks_attacker_weight 0 73 69 49 -23 0
ks_min_attackers 2
ks_hit 50
ks_weak_ring_square 100
ks_safe_check 0 555 489 473 555 0
ks_unsafe_check 151
ks_no_queen 938
ks_danger_div 5000
ks_shelter 176 40 108 132 140 135 102 55
ks_open_file 47
ks_storm 18 0 -107 53 73 19 -14 -4
ks_storm_blocked_div 4
ks_full_piece_material 12

# fit report (loss = valid loss by the real eval)
# tools/tune 0411135: set 8 from set 7, /home/ascanius/Documents/Cpp/other_programms/Chess/data/tune2
# positions: train 2455995, valid 304770, test 304116
# K 302.22 (fitted on set 7), lambda 1e-09, lr 2, epochs 1500, best epoch 902 (valid, model 0.113935), 661 s
# loss (sigma(basic_eval/K) - result)^2, real eval:
#   set   train      valid      test
#   7     0.114101   0.114206   0.114012
#   8     0.113840   0.113938   0.113743
# changed: 898 of 1065 weights; scalars:
#   piece_value_endgame[4]               2097 ->   2284
#   piece_value[4]                       1448 ->   1313
#   piece_value_endgame[1]               1242 ->   1334
#   piece_value[1]                        474 ->    408
#   piece_value_endgame[3]                740 ->    796
#   piece_value_endgame[2]                670 ->    724
#   ks_safe_check[1]                      599 ->    555
#   piece_value[3]                        385 ->    342
#   piece_value[2]                        308 ->    267
#   passed_supported[6]                   146 ->    177
#   ks_safe_check[2]                      518 ->    489
#   ks_no_queen                           965 ->    938
#   ks_safe_check[3]                      496 ->    473
#   mobility_queen_opening[20]            243 ->    221
#   mobility_queen_endgame[16]            315 ->    334
#   mobility_queen_endgame[17]            325 ->    344
#   mobility_queen_endgame[18]            331 ->    350
#   mobility_queen_endgame[20]            342 ->    361
#   pawn_phalanx_opening[5]                50 ->     69
#   mobility_queen_opening[19]            233 ->    215
#   mobility_queen_endgame[19]            336 ->    354
#   passed_pawn_value[1]                   97 ->    114
#   mobility_queen_opening[18]            210 ->    193
#   mobility_queen_opening[21]            273 ->    256
#   mobility_queen_endgame[15]            296 ->    313
#   ks_safe_check[4]                      572 ->    555
#   mobility_queen_endgame[14]            276 ->    292
#   ks_storm[2]                           -91 ->   -107
#   mobility_queen_opening[22]            302 ->    287
#   mobility_queen_opening[1]              78 ->     92
#   mobility_queen_opening[17]            198 ->    184
#   mobility_queen_endgame[12]            228 ->    242
#   mobility_queen_endgame[13]            246 ->    260
#   ks_shelter[7]                          41 ->     55
#   passed_free_path[6]                   155 ->    168
#   ks_shelter[6]                          89 ->    102
#   passed_pawn_value[6]                  209 ->    221
#   passed_unstoppable                     36 ->     48
#   mobility_queen_opening[16]            181 ->    169
#   mobility_queen_endgame[11]            205 ->    217
#   pawn_phalanx_endgame[4]               101 ->    113
#   pawn_phalanx_endgame[5]                35 ->     47
#   piece_value_endgame[0]                209 ->    220
#   ks_shelter[2]                          97 ->    108
#   mobility_knight_opening[0]            -27 ->    -37
#   mobility_bishop_endgame[0]            -38 ->    -48
#   mobility_bishop_endgame[12]           202 ->    212
#   mobility_queen_opening[15]            179 ->    169
#   mobility_queen_endgame[10]            174 ->    184
#   mobility_queen_endgame[21]            328 ->    338
#   ks_unsafe_check                       161 ->    151
#   passed_supported[5]                   178 ->    187
#   mobility_knight_endgame[8]            216 ->    225
#   mobility_bishop_endgame[10]           194 ->    203
#   mobility_bishop_endgame[11]           194 ->    203
#   mobility_rook_endgame[13]             206 ->    215
#   mobility_queen_opening[23]            328 ->    319
#   pawn_phalanx_endgame[6]                20 ->     29
#   ks_shelter[0]                         167 ->    176
#   ks_shelter[3]                         123 ->    132
#   passed_pawn_value[2]                   94 ->    102
#   mobility_knight_endgame[2]             76 ->     84
#   mobility_knight_endgame[5]            170 ->    178
#   mobility_knight_endgame[6]            187 ->    195
#   mobility_knight_endgame[7]            212 ->    220
#   mobility_bishop_endgame[9]            190 ->    198
#   mobility_rook_opening[13]             148 ->    140
#   mobility_rook_endgame[11]             203 ->    211
#   mobility_rook_endgame[12]             206 ->    214
#   mobility_rook_endgame[14]             204 ->    212
#   mobility_queen_opening[14]            171 ->    163
#   mobility_queen_endgame[9]             148 ->    156
#   rook_seventh_opening                  -43 ->    -51
#   ks_shelter[4]                         132 ->    140
#   ks_shelter[5]                         127 ->    135
#   passed_pawn_value_opening[5]           52 ->     45
#   mobility_knight_endgame[4]            134 ->    141
#   mobility_bishop_opening[12]           167 ->    160
#   mobility_bishop_opening[13]           214 ->    221
#   mobility_bishop_endgame[1]            -58 ->    -65
#   mobility_bishop_endgame[8]            181 ->    188
#   mobility_rook_opening[12]             121 ->    114
#   mobility_rook_opening[14]             164 ->    157
#   mobility_rook_endgame[9]              188 ->    195
#   mobility_rook_endgame[10]             199 ->    206
#   mobility_queen_opening[2]             100 ->    107
#   mobility_queen_endgame[8]             131 ->    138
#   mobility_queen_endgame[25]            363 ->    356
#   passed_pawn_value[3]                  108 ->    114
#   mobility_knight_endgame[3]            109 ->    115
#   mobility_bishop_endgame[6]            147 ->    153
#   mobility_bishop_endgame[7]            167 ->    173
#   mobility_rook_opening[10]              97 ->     91
#   mobility_rook_opening[11]             104 ->     98
#   mobility_rook_endgame[1]               42 ->     48
#   mobility_rook_endgame[5]              108 ->    114
#   mobility_rook_endgame[6]              126 ->    132
#   mobility_rook_endgame[7]              147 ->    153
#   mobility_rook_endgame[8]              170 ->    176
#   mobility_queen_opening[13]            172 ->    166
#   mobility_queen_opening[24]            351 ->    345
#   mobility_queen_endgame[22]            341 ->    347
#   mobility_queen_endgame[24]            347 ->    341
#   bishop_pair_endgame                   162 ->    168
#   rook_seventh_endgame                   63 ->     69
#   punishment_for_trippled_pawn           64 ->     69
#   passed_pawn_value[4]                  123 ->    128
#   passed_pawn_value_opening[6]          143 ->    138
#   passed_free_path[5]                    67 ->     72
#   mobility_knight_opening[1]            -12 ->    -17
#   mobility_bishop_endgame[4]             85 ->     90
#   mobility_bishop_endgame[5]            123 ->    128
#   mobility_rook_opening[9]               91 ->     86
#   mobility_rook_endgame[2]               49 ->     54
#   mobility_rook_endgame[3]               60 ->     65
#   mobility_rook_endgame[4]               88 ->     93
#   mobility_queen_opening[0]              10 ->     15
#   mobility_queen_opening[3]             109 ->    114
#   mobility_queen_opening[25]            369 ->    364
#   mobility_queen_endgame[4]              50 ->     45
#   mobility_knight_opening[2]             32 ->     28
#   mobility_knight_opening[3]             66 ->     62
#   mobility_knight_opening[4]             94 ->     90
#   mobility_knight_opening[5]            111 ->    107
#   mobility_knight_opening[6]            135 ->    131
#   mobility_knight_opening[7]            157 ->    153
#   mobility_knight_opening[8]            183 ->    179
#   mobility_knight_endgame[1]             20 ->     24
#   mobility_bishop_opening[4]             50 ->     46
#   mobility_bishop_opening[5]             72 ->     68
#   mobility_bishop_opening[6]             84 ->     80
#   mobility_bishop_opening[7]             98 ->     94
#   mobility_bishop_opening[8]            107 ->    103
#   mobility_bishop_opening[9]            127 ->    123
#   mobility_bishop_opening[10]           133 ->    129
#   mobility_bishop_opening[11]           159 ->    155
#   mobility_rook_opening[6]               67 ->     63
#   mobility_rook_opening[7]               76 ->     72
#   mobility_rook_opening[8]               83 ->     79
#   mobility_queen_opening[4]             113 ->    117
#   mobility_queen_opening[11]            159 ->    155
#   mobility_queen_opening[12]            162 ->    158
#   mobility_queen_endgame[7]             104 ->    108
#   mobility_queen_endgame[26]            388 ->    384
#   pawn_phalanx_opening[6]                 9 ->     13
#   threat_by_rook[1]                      -9 ->    -13
#   passed_free_path[4]                    21 ->     24
#   passed_king_enemy[1]                  -12 ->    -15
#   passed_king_enemy[5]                   75 ->     78
#   mobility_knight_endgame[0]             -9 ->    -12
#   mobility_bishop_opening[2]             18 ->     15
#   mobility_bishop_opening[3]             28 ->     25
#   mobility_bishop_endgame[3]             32 ->     35
#   mobility_rook_opening[3]               52 ->     49
#   mobility_rook_opening[4]               50 ->     47
#   mobility_rook_opening[5]               59 ->     56
#   mobility_queen_endgame[2]              29 ->     26
#   mobility_queen_endgame[6]              92 ->     95
#   mobility_queen_endgame[27]            408 ->    405
#   pawn_phalanx_opening[4]                83 ->     80
#   threat_by_pawn[0]                     -22 ->    -25
#   ks_weak_ring_square                    97 ->    100
#   ks_storm[4]                            76 ->     73
#   ks_storm[5]                            22 ->     19
#   ks_storm[6]                           -11 ->    -14
#   passed_pawn_value_opening[4]           22 ->     20
#   passed_free_path[1]                    20 ->     22
#   passed_free_path[2]                    -2 ->      0
#   passed_free_path[3]                     5 ->      7
#   passed_king_enemy[2]                   -8 ->    -10
#   passed_king_own[3]                     33 ->     35
#   passed_king_own[6]                     59 ->     61
#   passed_supported[4]                    72 ->     74
#   passed_rook_behind                     79 ->     81
#   activity_rook_attack                   30 ->     28
#   mobility_bishop_opening[1]             -3 ->     -5
#   mobility_bishop_endgame[2]            -14 ->    -12
#   mobility_bishop_endgame[13]           190 ->    192
#   mobility_rook_opening[1]               27 ->     25
#   mobility_rook_opening[2]               43 ->     41
#   mobility_queen_opening[5]             119 ->    121
#   mobility_queen_opening[10]            159 ->    157
#   mobility_queen_opening[26]            393 ->    391
#   mobility_queen_endgame[3]              43 ->     41
#   pawn_phalanx_endgame[3]                24 ->     26
#   bishop_pair_opening                     9 ->      7
#   threat_by_pawn[4]                     -13 ->    -15
#   threat_by_rook[4]                      48 ->     50
#   ks_attacker_weight[4]                 -25 ->    -23
#   ks_hit                                 48 ->     50
#   ks_storm[0]                            20 ->     18
#   ks_storm[7]                            -2 ->     -4
#   passed_pawn_value_opening[1]            6 ->      5
#   passed_king_own[1]                     19 ->     20
#   passed_king_own[2]                     21 ->     22
#   passed_king_own[4]                     46 ->     47
#   passed_king_own[5]                     54 ->     55
#   passed_supported[1]                    -2 ->     -1
#   passed_supported[3]                    40 ->     41
#   activity_pawn_attack                   78 ->     77
#   activity_pawn_push_attack              17 ->     16
#   activity_bishop_defend                 21 ->     22
#   activity_bishop_attack                 -9 ->    -10
#   activity_queen_defend                  14 ->     13
#   activity_queen_attack                  -5 ->     -6
#   activity_knight_attack                 -2 ->     -3
#   activity_king_defend                    8 ->      9
#   activity_king_attack                   38 ->     39
#   mobility_bishop_opening[0]            -33 ->    -34
#   mobility_rook_endgame[0]               -7 ->     -8
#   mobility_queen_opening[6]             127 ->    128
#   mobility_queen_opening[7]             136 ->    137
#   mobility_queen_opening[8]             142 ->    141
#   mobility_queen_opening[9]             149 ->    148
#   mobility_queen_opening[27]            410 ->    409
#   mobility_queen_endgame[5]              77 ->     78
#   mobility_queen_endgame[23]            338 ->    337
#   pawn_phalanx_opening[2]                12 ->     11
#   pawn_phalanx_opening[3]                39 ->     38
#   pawn_phalanx_endgame[2]                -6 ->     -5
#   rook_open_file_opening                 60 ->     61
#   rook_open_file_endgame                 28 ->     27
#   rook_semi_open_file_opening            30 ->     31
#   rook_semi_open_file_endgame            28 ->     27
#   outpost_knight_opening                 26 ->     25
#   outpost_knight_endgame                 35 ->     36
#   outpost_bishop_opening                 29 ->     30
#   threat_by_pawn[1]                      19 ->     20
#   threat_by_pawn[2]                       8 ->      7
#   threat_by_pawn[3]                     -11 ->    -12
#   threat_by_minor[0]                     -4 ->     -3
#   threat_by_minor[1]                     80 ->     81
#   threat_by_minor[2]                     74 ->     75
#   threat_by_rook[0]                     -32 ->    -31
#   threat_by_rook[2]                       8 ->      9
#   threat_by_rook[3]                      14 ->     15
#   ks_attacker_weight[2]                  68 ->     69
#   ks_open_file                           48 ->     47
#   ks_storm[3]                            54 ->     53
)WEIGHTS";
#endif // WEIGHTS_DEFAULT_HPP
